site_name: 名字竞技场教程
nav:
  - 首页: 'index.md'
  - 基础教程:
    - 1 名竞本身与玩法: 'chp1.md'
    - 2 测号技术: 'chp2.md'
    - 3 交流平台与提问的艺术: 'chp3.md'
  - 进阶教程:
    - 1 基础知识: 'ex-chp1.md'
    - 2 实战特点与环境分析（上）: 'ex-chp2.md'
    - 3 实战特点与环境分析（下）: 'ex-chp3.md'
    - 4 pbb 测号器的使用: 'ex-chp4.md'
    - 5 进阶开箱技术简介: 'ex-chp5.md'
    - 6 node 开箱器操作指南: 'ex-chp6.md'
    - 7 二人组模型拟合配队: 'ex-chp7.md'
    - 8 简易算号原理: 'ex-chp8.md'
  - 拓展研究:
    - 1 算号代码解析与优化[WIP]: 'deep-chp1.md'
    - 2 游戏机理与机制理解: 'deep-chp2.md'
  - 配套资源:
    - 资源文件下载: 'res-files.md'
    - 算号代码获取: 'res-namecalc-code.md'
  - 史料选读:
    - 入门 Q&A: 'doc-qa-for-noobs.md'
    - Rinick 二人组: 'doc-rinick-duos.md'
    - 浅谈战队发展: 'doc-qtzdfz.md'
    - MD5 大作战历史: 'doc-md5.md'
theme:
  name: readthedocs
  highlightjs: False
  prev_next_buttons_location: none
  locale: zh_CN
plugins: []
